#!/bin/bash

set -eu

ZIPNAME=firefox-nightly.tar.bz2
DIRNAME=firefox-nightly

if [[ "$(uname -m)" == "x86_64" ]];then
	cd /tmp
	wget "https://download.mozilla.org/?product=firefox-nightly-latest-l10n-ssl&os=linux64&lang=ja" -O $ZIPNAME
	which pbzip2 && OPT=--use-compress-prog=pbzip2
	tar xvf $ZIPNAME $OPT
	rm -rf $MYLOCAL/opt/$DIRNAME
	mv firefox $MYLOCAL/opt/$DIRNAME
	ln -s $MYLOCAL/opt/$DIRNAME/firefox $MYLOCAL/bin/firefox-nightly
fi
