#!/bin/bash

set -eu

pushd $PWD
	cd /tmp
	if which curl >/dev/null 2>&1 ;then
		curl -L https://github.com/git/git/archive/master.zip -o git.zip
	elif which wget >/dev/null 2>&1 ;then
		wget https://github.com/git/git/archive/master.zip -O /tmp/brew.zip
	else
		echo "curl or wget not found."
	fi
	unzip git.zip
	cd git-master
	make configure
	./configure --prefix=$MYLOCAL --with-openssl --with-curl --with-expat
	make -j4
	#make -j4 test
	make -j4 install
	cd ..
	rm git.zip
	rm -rf git-master
popd
