#!/bin/bash

set -eu

URL="https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb"

if [[ "$(uname -m)" == "x86_64" ]];then
	cd /tmp
	wget $URL -O $MYLOCAL/tmp/google-chrome-unstable_current_amd64.deb
	#mv firefox $MYLOCAL/opt/$DIRNAME
	#ln -s $MYLOCAL/opt/$DIRNAME/firefox $MYLOCAL/bin/firefox-nightly
fi
