#!/bin/bash

set -eu
source lib.sh

dfpm "PapirusDevelopmentTeam/papirus-icon-theme" $MYLOCAL/tmp

pushd "$PWD"
	ICONS="ePapirus Papirus Papirus-Dark Papirus-Light Papirus-Adapta Papirus-Adapta-Nokto"
	for i in $ICONS ;do
		echo $i
		cp -r $MYLOCAL/tmp/papirus-icon-theme/$i $MYLOCAL/usr/share/icons
		ln -s $MYLOCAL/usr/share/icons/$i $XDG_DATA_HOME/icons
		gtk-update-icon-cache -q $XDG_DATA_HOME/icons/$i
	done
popd
