#!/bin/bash

set -eu

pushd $PWD
	cd /tmp
	if which wget >/dev/null 2>&1 ;then
		wget https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz -O pkgconfig.tar.gz
	else
		echo "wget not found."
	fi
	tar xvf pkgconfig.tar.gz
	cd pkg-config-0.29.2
	./configure --prefix=$MYLOCAL --with-internal-glib
	make -j4
	make install
	cd ..
	rm pkgconfig.tar.gz
	rm -rf pkg-config-0.29.2
popd
