#!/bin/bash

set -eu

CTG=$HOME/.conf-to-git
MYLOCAL=$CTG/local

touch $HOME/.zprofile.local
source $HOME/.zprofile.local

BREW_VERSION="1.3.6"
#MYLOCAL=$PWD/local
LINUXBREW=$MYLOCAL/Linuxbrew
ANYENV=$MYLOCAL/anyenv

if ! which curl >/dev/null 2>&1;then
	$CTG/provision/Curl
fi

if ! which git >/dev/null 2>&1;then
	$CTG/provision/Git
fi

#if which git >/dev/null 2>&1 ;then
	git submodule init
	git submodule update
#else
#	echo "git not found. Please run 10-main again after install git."
#fi

if [[ ! -e "$MYLOCAL" ]];then
	mkdir -p $MYLOCAL
fi

#if [[ ! -e ./local ]];then
#	ln -s $MYLOCAL ./local
#fi

if [[ ! -e "$LINUXBREW" ]];then
	#git clone -b $BREW_VERSION --depth 1 https://github.com/Linuxbrew/brew $LINUXBREW

	if which git >/dev/null 2>&1 ;then
		git clone --depth 1 https://github.com/Linuxbrew/brew $LINUXBREW
	elif which curl >/dev/null 2>&1 ;then
		pushd $PWD
		cd /tmp
			curl -L https://github.com/Linuxbrew/brew/archive/master.zip -o /tmp/brew.zip
			unzip /tmp/brew.zip
			mv /tmp/brew-master $LINUXBREW
		popd
		rm /tmp/brew.zip
	elif which wget >/dev/null 2>&1 ;then
		pushd $PWD
		cd /tmp
			wget https://github.com/Linuxbrew/brew/archive/master.zip -O /tmp/brew.zip
			unzip /tmp/brew.zip
			mv /tmp/brew-master $LINUXBREW
		popd
		rm /tmp/brew.zip
	else
    echo "curl or wget not found."	
	fi
fi

#if [[ ! -e "$ANYENV" ]];then
#	git clone --depth 1 https://github.com/riywo/anyenv $ANYENV
#fi

#brew install git ruby git-lfs
#export PATH=/home/local/python/anaconda3/bin:$PATH
#export HOMEBREW_CURL=/home/local/python/anaconda3/bin/curl

#brew uses --installed curl
#ln -s /home/local/python/anaconda3/bin/curl $MYLOCAL/Linuxbrew/bin/curl
#export HOMEBREW_CURL=$MYLOCAL/Linuxbrew/bin/curl
#brew update
#brew install ansible

cd $CTG/zsh >/dev/null && ./make >/dev/null

ln -sf $CTG/config/tmux.conf ~/.tmux.conf
ln -sf $CTG/config/ssh-config ~/.ssh/config
ln -sf $CTG/config/gitconfig ~/.gitconfig
ln -sf $CTG/config/yaourtrc ~/.yaourtrc
ln -sf $CTG/config/locale.conf ~/.config/locale.conf
ln -sf $CTG/config/w3mconfig ~/.config/.w3mconfig
ln -sf $CTG/vim/vimrc ~/.vimrc
ln -sf $CTG/zsh/zshrc ~/.zshrc
#ln -sf $CTG/zsh/zshrc ~/.zshrc
echo 'export CTG=$HOME/.conf-to-git' > ~/.zprofile
echo "export MYLOCAL=$MYLOCAL" >> ~/.zprofile
echo 'source $HOME/.zprofile.local' >> ~/.zprofile
echo 'source $CTG/zsh/zprofile' >> ~/.zprofile

touch ~/.zshrc.local
#touch ~/.zprofile.local

mkdir -p $MYLOCAL/usr/share/icons
mkdir -p $MYLOCAL/usr/lib/locale
mkdir -p $MYLOCAL/tmp
mkdir -p $MYLOCAL/opt
mkdir -p $MYLOCAL/lib
mkdir -p $MYLOCAL/etc
mkdir -p $MYLOCAL/bin
mkdir -p $MYLOCAL/share
mkdir -p $MYLOCAL/local

#exec zsh -l
echo Run zsh.
