#!/bin/bash

set -eu

CTG=$HOME/.conf-to-git
MYLOCAL=$CTG/local

touch $HOME/.zprofile.local
source $HOME/.zprofile.local

BREW_VERSION="1.3.6"
#MYLOCAL=$PWD/local
LINUXBREW=$MYLOCAL/Linuxbrew
ANYENV=$MYLOCAL/anyenv

if ! which pkg-config >/dev/null 2>&1;then
	$CTG/provision/Pkgconfig
fi

if ! which curl >/dev/null 2>&1;then
	$CTG/provision/Libressl
	$CTG/provision/Curl
fi

if ! which git >/dev/null 2>&1;then
	$CTG/provision/Git
fi

git submodule init
git submodule update
if [[ ! -e "$MYLOCAL" ]];then
	mkdir -p $MYLOCAL
fi

if [[ ! -e "$LINUXBREW" ]];then
	git clone -b $BREW_VERSION --depth 1 https://github.com/Linuxbrew/brew $LINUXBREW
	#git clone --depth 1 https://github.com/Linuxbrew/brew $LINUXBREW
fi

if [[ ! -e "$ANYENV" ]];then
	git clone --depth 1 https://github.com/riywo/anyenv $ANYENV
fi

check_locale="$MYLOCAL/usr/lib/locale"
if ! (ls $check_locale|grep ja_JP) || ! (ls $check_locale|grep en_US) ;then
	echo "There are not ja_JP and en_US."
	cp /etc/locale.gen $MYLOCAL/etc/locale.gen
	echo "ja_JP.UTF-8 UTF-8" >> $MYLOCAL/etc/locale.gen
	echo "en_US.UTF-8 UTF-8" >> $MYLOCAL/etc/locale.gen
	locale-gen.local
fi

cd $CTG/zsh >/dev/null && ./make >/dev/null
ln -sf $CTG/config/tmux.conf ~/.tmux.conf
ln -sf $CTG/config/ssh-config ~/.ssh/config
ln -sf $CTG/config/gitconfig ~/.gitconfig
ln -sf $CTG/config/yaourtrc ~/.yaourtrc
ln -sf $CTG/config/locale.conf ~/.config/locale.conf
ln -sf $CTG/config/w3mconfig ~/.config/.w3mconfig
ln -sf $CTG/vim/vimrc ~/.vimrc
ln -sf $CTG/zsh/zshrc ~/.zshrc
#ln -sf $CTG/zsh/zshrc ~/.zshrc
echo 'export CTG=$HOME/.conf-to-git' > ~/.zprofile
echo "export MYLOCAL=$MYLOCAL" >> ~/.zprofile
echo 'source $HOME/.zprofile.local' >> ~/.zprofile
echo 'source $CTG/zsh/zprofile' >> ~/.zprofile

touch ~/.zshrc.local
#touch ~/.zprofile.local

mkdir -p $MYLOCAL/usr/share/icons
mkdir -p $MYLOCAL/usr/lib/locale
mkdir -p $MYLOCAL/tmp
mkdir -p $MYLOCAL/opt
mkdir -p $MYLOCAL/lib
mkdir -p $MYLOCAL/etc
mkdir -p $MYLOCAL/bin
mkdir -p $MYLOCAL/share
mkdir -p $MYLOCAL/local

#exec zsh -l
echo Run zsh.
