#!/bin/bash

set -eu

PYTHON_VERSION2=2.7.14
PYTHON_VERSION3=3.6.3
RUBY_VERSION=2.4.2

#PATH=$PWD/anyenv/bin:$PATH
#ANYENV_ROOT=$PWD/anyenv
#eval "$(anyenv init -)"
anyenv install -s rbenv
anyenv install -s pyenv

eval "$(anyenv init -)"

pyenv install -sv $PYTHON_VERSION2

pyenv install -sv $PYTHON_VERSION3
pyenv global $PYTHON_VERSION2 $PYTHON_VERSION3 $PYTHON_VERSION2

CONFIGURE_OPTS="--disable-install-rdoc" rbenv install -sv $RUBY_VERSION

echo Run zsh.
