#!/bin/bash
CTG=$HOME/.conf-to-git
MYLOCAL=$CTG/local

source $HOME/.zprofile.local

BREW_VERSION="1.3.6"
#MYLOCAL=$PWD/local
LINUXBREW=$MYLOCAL/Linuxbrew
ANYENV=$MYLOCAL/anyenv

git submodule init
git submodule update

if [[ ! -e "$MYLOCAL" ]];then
	mkdir -p $MYLOCAL
fi

#if [[ ! -e ./local ]];then
#	ln -s $MYLOCAL ./local
#fi

if [[ ! -e "$LINUXBREW" ]];then
	#git clone -b $BREW_VERSION --depth 1 https://github.com/Linuxbrew/brew $LINUXBREW
	git clone --depth 1 https://github.com/Linuxbrew/brew $LINUXBREW
fi

if [[ ! -e "$ANYENV" ]];then
	git clone --depth 1 https://github.com/riywo/anyenv $ANYENV
fi

#brew install git ruby git-lfs
#export PATH=/home/local/python/anaconda3/bin:$PATH
#export HOMEBREW_CURL=/home/local/python/anaconda3/bin/curl

#brew uses --installed curl
#ln -s /home/local/python/anaconda3/bin/curl $MYLOCAL/Linuxbrew/bin/curl
#export HOMEBREW_CURL=$MYLOCAL/Linuxbrew/bin/curl
#brew update
#brew install ansible

cd zsh >/dev/null && ./make && cd ../ >/dev/null

ln -sf $CTG/vim/vimrc ~/.vimrc
ln -sf $CTG/config/tmux.conf ~/.tmux.conf
ln -sf $CTG/zsh/zshrc ~/.zshrc
#ln -sf $CTG/zsh/zshrc ~/.zshrc
echo 'export CTG=$HOME/.conf-to-git' > ~/.zprofile
echo 'export MYLOCAL=$MYLOCAL' >> ~/.zprofile
echo 'source $HOME/.zprofile.local' >> ~/.zprofile
echo 'source $CTG/zsh/zprofile' >> ~/.zprofile

touch ~/.zshrc.local
touch ~/.zprofile.local

#exec zsh -l
echo Run zsh.
