set autoread
set cursorline
set fenc=utf-8
set hidden
set laststatus=2
set nobackup
set noswapfile
set number
set showcmd
set showmatch
set smartindent
set virtualedit=onemore
set visualbell
set wildmode=list:longest
set tabstop=2
set shiftwidth=2
set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch
set clipboard=unnamed
set relativenumber
set noexpandtab
set nocompatible
set backspace=indent,eol,start
"noremap PP "0p
"noremap x "_x

set runtimepath+=$CTG/vim/dein.vim
if dein#load_state("$CTG/local/vim-plugins")
	call dein#begin(expand("$CTG/local/vim-plugins"))
	call dein#load_toml(expand("$CTG/vim/dein.toml"),{'lazy': 0})
	call dein#load_toml(expand("$CTG/vim/dein_lazy.toml"),{'lazy': 1})
	call dein#end()
	call dein#save_state()
endif

syntax enable
filetype plugin indent on

if dein#check_install()
  call dein#install()
endif

colorscheme badwolf
highlight Normal ctermbg=none
