[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

#[[plugins]]
#repo = 'posva/vim-vue'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'neoclide/coc-neco'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'jsfaint/coc-neoinclude'

#[[plugins]]
#repo = 'liuchengxu/vista.vim'

#[[plugins]]
#repo = 'glacambre/firenvim'
#hook_post_update = '''
#  call firenvim#install(0)
#'''

#[[plugins]]
#repo = 'mbbill/undotree'

#[[plugins]]
#repo = 'yuttie/comfortable-motion.vim'
