#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#fcitx-autostart &
#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login
#exec xmonad
#xscreensaver &
#/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets

#setxkbmap -layout jp
export GTK_IM_MODULE='ibus'
export QT_IM_MODULE='ibus'
export XMODIFIERS='@im=ibus'
#uim-xim &
ibus-daemon -drx &
export LANG=ja_JP.UTF-8


#cinnamon-screensaver &
#plank &
#albert &
#guake &
#thunar --daemon &
#redshift-gtk &
#libinput-gestures-setup start &
#jack_control start &

#conky &

#compton --config ~/.compton.conf &
#xss-lock -- i3lock -n -i $HOME/.conf-to-git/mojave_dynamic_8.resize.png &
exec startxfce4
