alias ls='exa --all --binary --group --header --links --inode --git --icons --classify --group-directories-first --git'
alias cat='bat --theme="Solarized (dark)"'
alias find='fd'
#alias ps='procs'
alias grep='rg'
alias diff='diff-so-fancy-standalone'
alias git='hub'
#alias ssh='xxh'
alias ping='prettyping'


## colorize (no feature) ##
alias make='colormake'
alias df='grc df'
alias ./configure='grc ./configure'
alias du='grc du'
alias env='grc env'
alias id='grc id'
alias ip='grc ip'
alias jobs='grc jobs'
alias lsblk='grc lsblk'
alias lsmod='grc lsmod '
alias lspci='grc lspci'
alias mount='grc mount'
alias nmap='grc nmap'
alias ps='grc ps'
alias ss='grc ss'
alias sysctl='grc sysctl'
alias systemctl='grc systemctl'
alias tcpdump='grc tcpdump'
alias uptime='grc uptime'
alias vmstat='grc vmstat'
alias whois='grc whois'
alias du='dutree'

export PATH="/usr/lib/colorgcc/bin:$PATH"
export PATH="/usr/share/perl5/vendor_perl/auto/share/dist/Cope:"$PATH
