alias ls='exa --all --binary --group --header --links --inode --git --icons --classify --group-directories-first --git'
alias cat='bat --theme="Solarized (dark)"'
alias find='fd'
#alias ps='procs'
alias grep='rg'
alias diff='diff-so-fancy-standalone'
alias git='hub'
alias ssh='xxh'
