#!/bin/bash

touch zshrc
echo -n > zshrc
command ls ./zshrc.d/*.zsh | sort | tee /dev/stderr | xargs cat >> ./zshrc
find ./zshrc.d/hooks -name *.zsh | sort | tee /dev/stderr | xargs zsh >> ./zshrc
zsh -n zshrc
zsh -c 'zcompile ~/.zshrc'

touch zprofile
echo -n > zprofile
find ./zprofile.d -name *.zsh | sort | xargs cat >> ./zprofile
