#!/usr/bin/env bash

function mes_info(){
	tput setaf 11
	echo -n $1
	tput setaf 10
	echo -n " $2..."
	tput sgr0
}
function mes_done(){
	tput setaf 10
	echo 'done'
	tput sgr0
}

mes_info '[zshrc]' 'init'
	touch zshrc
	echo -n > zshrc
	rm -f ~/.zcompdump
mes_done

mes_info '[zshrc]' 'Bundle zshrc.d'
	command ls ./zshrc.d/*.zsh       | sort | xargs cat >> ./zshrc
mes_done

mes_info '[zshrc]' 'Bundle hooks'
	find ./zshrc.d/hooks -name *.zsh | sort | xargs zsh >> ./zshrc
mes_done

mes_info '[zshrc]' 'Test & Compile'
	zsh -n zshrc
	zsh -c 'zcompile ~/.zshrc'
mes_done


mes_info '[zprofile]' 'init'
	touch zprofile
	echo -n > zprofile
mes_done

mes_info '[zprofile]' 'Bundle zprofile.d'
	find ./zprofile.d -name *.zsh | sort | xargs cat >> ./zprofile
mes_done

mes_info '[zprofile]' 'Test & Compile'
	zsh -n zprofile
	zsh -c 'zcompile ./zprofile'
mes_done
